### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by peterennis** [stencil-community/stencil-app-starter#71] opened 2019-06-23 03:19 UTC
at this commit: https://github.com/ionic-team/stencil-app-starter/commit/0853cbcad7c9933d04b45109ae1dcdbfe759d475

![Capture587](https://user-images.githubusercontent.com/140737/59971099-69efd080-952a-11e9-850f-3d999d578569.png)

```
C:\ae\stencil-app-starter>npmtest
'npmtest' is not recognized as an internal or external command,
operable program or batch file.

C:\ae\stencil-app-starter>npm test

> stencil-starter-project-name@0.0.1 test C:\ae\stencil-app-starter
> stencil test --spec --e2e

[09:04.3]  Please wait while required dependencies are installed. This may take a few moments and will only be
           required for the initial run.
[09:04.3]  installing dependencies: @types/jest, jest, jest-cli, @types/puppeteer, puppeteer ...
Downloading Chromium r662092 - 140.3 Mb [====================] 100% 0.0s
+ jest-cli@24.8.0
+ jest@24.8.0
+ puppeteer@1.17.0
+ @types/jest@24.0.15
+ @types/puppeteer@1.12.4
added 504 packages from 414 contributors in 115.593s
[11:02.5]  installing dependencies finished in 118.18 s
[11:02.7]  @stencil/core v1.0.7
[11:02.7]  testing e2e and spec files
[11:02.7]  build, app, dev mode, started ...
[11:03.7]  transpile started ...
[11:07.5]  transpile finished in 3.75 s
[11:07.5]  generate styles started ...
[11:07.5]  bundling components started ...
[11:08.8]  generate styles finished in 1.31 s
[11:10.3]  bundling components finished in 2.80 s
[11:10.5]  build finished in 7.80 s

 PASS  src/components/app-profile/app-profile.spec.ts (5.831s)
 PASS  src/components/app-profile/app-profile.e2e.ts (9.703s)
  ● Console

    console.error node_modules/@stencil/core/dist/testing/index.js:39072
      Failed to load resource: the server responded with a status of 404 (Not Found)
    console.error node_modules/@stencil/core/dist/testing/index.js:39082
      requestfailed http://localhost:3333/build/app.css

 PASS  src/components/app-home/app-home.e2e.ts (9.826s)
 PASS  src/components/app-root/app-root.e2e.ts (5.357s)
  ● Console

    console.error node_modules/@stencil/core/dist/testing/index.js:39072
      Failed to load resource: the server responded with a status of 404 (Not Found)
    console.error node_modules/@stencil/core/dist/testing/index.js:39082
      requestfailed http://localhost:3333/build/app.css
    console.error node_modules/@stencil/core/dist/testing/index.js:39072
      Failed to load resource: the server responded with a status of 404 (Not Found)
    console.error node_modules/@stencil/core/dist/testing/index.js:39082
      requestfailed http://localhost:3333/build/app.css

 PASS  src/components/app-root/app-root.spec.ts
 PASS  src/components/app-home/app-home.spec.ts

Test Suites: 6 passed, 6 total
Tests:       14 passed, 14 total
Snapshots:   0 total
Time:        13.723s
Ran all test suites.

ERROR: The process with PID 2892 (child process of PID 9644) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 21836 (child process of PID 9644) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 18468 (child process of PID 9644) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 21692 (child process of PID 9644) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 11636 (child process of PID 9644) could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process with PID 15836 (child process of PID 9644) could not be terminated.
Reason: There is no running instance of the task.

C:\ae\stencil-app-starter>
```

**Comment by peterennis** [comment] 2019-06-23 03:20
@manucorporat 
The starter builds and runs but there are lots of console errors.

**Comment by Mouvedia** [comment] 2019-07-03 09:40
I am experiencing the same error.

stencil version: 1.1.3

**Comment by ng-model** [comment] 2020-09-11 14:17
did you find any solution ? @peterennis  @Mouvedia Thanks

**Comment by david-poindexter** [comment] 2022-05-22 19:45
This issue appears to have been resolved somewhere along the way, as I am unable to reproduce it at this time.  We'll go ahead and close this issue for now, but please feel free to reply if you are still having issues and need this issue reopened.  Thanks!

**Closed by david-poindexter** 2022-05-22 19:45 UTC
