### ISSUE TITLE
Build Error EEXIST: file already exists, copyfile icon.png

### ISSUE THREAD

**Issue by jocubeit** [stencil-community/stencil-app-starter#66] opened 2019-03-16 06:28 UTC
Fresh build using `stencil init` and choosing app starter option. Build runs first time... subsequent start or build fails with this error.

Completely unusable.

**Comment by R0muald** [comment] 2019-03-26 20:50
Getting the same issue with v0.18.1.
I'm simply copying some CSS from a node module to get it referenced part of the `index.html` file.

**Comment by mariatamayo** [comment] 2019-03-26 21:45
Getting the same issue with v0.18.0.

**Comment by Nightbr** [comment] 2019-04-16 09:37
Same here on another Stenciljs project with svg assets (on icon):

`[ ERROR ]  EEXIST: file already exists, copyfile`

"@stencil/core": "^0.18.1",
node v11.14.0
npm 6.7.0

**Comment by david-poindexter** [comment] 2022-05-22 19:33
I have been unable to reproduce this issue using `npm start stencil app` (per `README`).

![image](https://user-images.githubusercontent.com/4568451/169712725-b7de0cc7-4523-4a95-8a24-2cd6d9eee55f.png)

![image](https://user-images.githubusercontent.com/4568451/169712736-2f72c78c-2fb1-4376-b57c-41f619c5a82e.png)

We'll go ahead and close this issue for now, but feel free to reply if this is still an issue.

**Closed by david-poindexter** 2022-05-22 19:33 UTC
